apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-hello-world
  template:
    metadata:
      labels:
        app: private-hello-world
    spec:
      containers:
      - image: okteto/hello-world:golang
        name: hello-world

---

apiVersion: v1
kind: Service
metadata:
  name: private-hello-world
  annotations:
    dev.okteto.com/auto-ingress: "private"
spec:
  type: ClusterIP  
  ports:
  - name: "private-hello-world"
    port: 8080
  selector:
    app: private-hello-world
