apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-hello-world
  template:
    metadata:
      labels:
        app: private-hello-world
    spec:
      containers:
      - image: okteto/hello-world:golang
        name: hello-world

---

apiVersion: v1
kind: Service
metadata:
  name: private-hello-world
spec:
  type: ClusterIP  
  ports:
  - name: "private-hello-world"
    port: 8080
  selector:
    app: private-hello-world

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    dev.okteto.com/generate-host: "true"
    dev.okteto.com/private: "true"
  name: private-hello-world
spec:
  rules:
    - host: okteto
      http:
        paths:
          - path: /
            backend:
              serviceName: private-hello-world
              servicePort: 8080
